# project
task_name: "train_frag_transformer_smiles_100k"
device: "cuda"
train_data_path: "frag/runtime/frag_train_head100k.csv"
val_data_path: "frag/runtime/frag_val_head10k.csv"
word_table_path: "frag/smiles_word_table.yaml"
data_format: "SMILES"
data_cols: ["core", "frag_a", "frag_b"]

# train
learning_rate: 1.0e-4
min_learning_rate: 5.0e-5
# warming_steps * bsz / all_size = proportion
warming_step: 1562   # 50% epoch
weight_decay: 1.0e-5
batch_size: 128
epoch_num: 50
log_interval: 50
seed: 42
save_interval: 1

# model
max_len: 250
left_pad: False
d_model: 512
n_head: 8
d_enc_ffn: 1024
d_dec_ffn: 1024
enc_n_layer: 3
dec_n_layer: 4
enc_dropout: 0.2
dec_dropout: 0.2
enc_embed_dropout: 0.15
dec_embed_dropout: 0.15
enc_relu_dropout: 0.1
dec_relu_dropout: 0.1
enc_attn_dropout: 0.15
dec_attn_dropout: 0.15